---
title: "Beklenen İstanbul Depremi Üzerine Bir Araştırma"
author: 
  - Hakan Burak Günyel[^1]
bibliography: ../bibliography/biblio.bib
csl: ../csl/apa-tr.csl
header-includes:
  - \usepackage{polyglossia}
  - \setmainlanguage{turkish}
  - \usepackage{booktabs}
  - \usepackage{caption} 
  - \captionsetup[table]{skip=10pt}
output:
  bookdown::pdf_document2:
    fig_caption: yes
    fig_height: 3
    fig_width: 4
    keep_tex: no
    latex_engine: xelatex
    number_sections: yes
    toc: no
geometry: margin=1in
link-citations: yes
urlcolor: blue
fontsize: 12pt
biblio-style: apalike
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = FALSE, echo = TRUE, message = FALSE, warning = FALSE)
```

<!-- ======================================================================= -->
<!-- ============================== NOTLAR ================================= -->
<!-- ======================================================================= -->
[^1]: 21080549, [Github Repo](https://github.com/hakanburakgunyel/arasinav)

# Vize Hakkında Önemli Bilgiler

\colorbox{BurntOrange}{GITHUB REPO BAĞLANTINIZI BU DOSYANIN 35. SATIRINA YAZINIZ!}

**Proje önerisi gönderimi, Github repo linki ile birlikte ekampus sistemine bir zip dosyası yüklenerek yapılacaktır. Sisteme zip dosyası yüklemezseniz ve Github repo linki vermezseniz ara sınav ve final sınavlarına girmemiş sayılırsınız.**

**Proje klasörünüzü sıkıştırdıktan sonra (`YourStudentID.zip` dosyası) 16 Nisan 2023 23:59'a kadar *ekampus.ankara.edu.tr* adresine yüklemeniz gerekmektedir.**

\colorbox{WildStrawberry}{Daha fazla bilgi için proje klasöründeki README.md dosyasını okuyunuz.}

# Giriş
6 Şubat 2023 tarihinde merkez üssü Kahramanmaraş olan, iki büyük şiddetli deprem gerçekleşmiştir. Resmi rakamlara göre yaklaşık 50.000 vatandaşımız hayatını kaybetmiştir. Yaşanan bu felaketten sonra akıllara beklenen İstanbul depreminin ne zaman olacağı, yaratacağı yıkımın nasıl bir şiddette olacağı soruları akla getirmiştir. Araştırmaya bu sorular üzerine başlanmaya karar verilmiştir. İlk olarak konuyla alakalı İstanbul Büyükşehir Belediyesi’nin İBB Açık Veri Portalı üzerinden yayınladığı “Deprem Senaryosu Analiz Sonuçları” adlı veri setini bulunmuştur. Veri seti 7.5 Mw büyüklüğünde gece olacak deprem senaryosuna göre yapılan analizlerin sonuçlarını içermektedir. Veri seti 960 gözlem, 16 gözlem içermektedir.  Çalışma kolaylığı olması açısından gözlem sayısı elenerek çalışmaya eklenebilir.



## Çalışmanın Amacı
Çalışmanın amacı beklenen İstanbul depreminin yaratacağı hasarı İstanbul’un ilçeleri; mahalleleri; çok ağır, ağır, orta ve hafif hasarlı bina sayısı; can kaybı sayısı; ağır yaralı sayısı; hafif yaralı sayısı; hastanede tedavi sayısı; doğalgaz borusu, atık su borusu ve içme suyu borusu hasarı sayısı; geçici barınma sayıları değişkenleri üzerinden incelenmesini amaçlayan, içinde tablo ve grafiklerin bulunduğu istatiksel bir analiz yapmaktır.

## Literatür 
Depremler Dünyada kırık hatlar boyunca biriken enerjinin ani bir şekilde boşalması sonucu oluşan doğal afetlerdir. Dünya genelinde yılda 500.00 deprem olur ve bunların 100 ü binalara hasar verecek kadar güçlüdür. 17 Ağustos 1999 depreminden sonra yapılan araştırmalar Marmara Denizinde hala kırılmayan faylar olduğunu gösterir. Tom Parsons’ ın 2000 yılında yaptığı bir çalışma beklenen depremin 2000 ila 2030 yılları arasında olacağını gösterir. İstanbul,tarihi, coğrafyası, sosyal ve kültürel yönü bakımından oldukça zengin bir şehirdir. Büyük bir depremi yaşaması durumunda sadece Türkiye için değil, dünya birikimi açısından büyük bir kayıp yaşanır.[@csimcsek2021big]
Türkiye deprem kuşağında olmasına rağmen olası depremin yaratacağı hasara karşı hazırlıksızdır. Şehirlerimizde hızlı ve yoğun kentleşme beraberinde plansız yapılaşmayı beraberinde getirir.  Bu da kayıpların önünü açacaktır. Marmara bölgesi tarihimizde büyük yıkıcı depremlerle karşılaşmıştır. Yapılan çalışmalar büyük bir depremin tekrar yaşanacağını öngörmektedir. Böyle bir duruma hazırlıklı olmayan İstanbul’ da ciddi sayılarda can ve mal kaybının yaşanacağı tahmin edilmektedir. [@uyar2023deprem]
Deprem tehlikesi, arazi kullanımı, demografik yapı ve ekonomik yapı depremin riskini etkileyen temel faktörlerdir.  Depremin tehlikesini başta depremin büyüklüğü belirler. Konut alanlarındaki yoğunluk, nüfusun büyüklüğüyle doğru orantılıdır. Doğal afetler açısından bakıldığında en çok hasar yerler konut alanlarıdır. Konut alanlarının yapısal özelliklerinin belirlenmesi hasar tahmini yapmaya kolaylık sağlar. İstanbul’da depreme bağlı risk düzeylerini belirleyen ana bileşenler belirlenmiştir. Bu bağlamda hasar görebilirlik (mahallenin yaşı, yapı stoğu ve demografik yapısı incelenir), yoğunluk (mahalledeki yapı ve nüfus yoğunluğu incelenir), işyeri ve yanıcı/patlayıcı kullanımlar, tehlike (depremin yaratacağı ivme tepki spektrum değeri), ve potansiyeller (mahalledeki sağlık tesisi ve hasta yatak sayısı) incelenir. Sonuç olarak kentsel arazi kullanımı beraberinde nüfus yoğunluğunu getirir ve bahsedilen ana bileşenlerle birlikte depreme bağlı riski artırır. [@kundak2010istanbul]
Deprem riskine karşı insanlara farkındalık eğitimi verilmeli; kentsel dönüşüm ve altyapı çalışmaları yapılarak önlemler alınmalıdır. Depremle ilgili gerekli kanuni önlemler alınmalı, zorunlu deprem sigortası vatandaşlara yaptırılmalıdır. Türkiye’nin en önemli sanayi ve finans merkezi olan İstanbul’da yıkıcı bir depremin meydana gelmesi ekonomi ve endüstri faaliyetlerini durma noktasına getirebilir. [@erdik2008earthquake]

 



**_Taslakta bu cümleden sonra yer alan hiçbir şey silinmemelidir._**

\newpage
# Kaynakça {#references}
<div id="refs"></div>

